name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to print'
        required: false
        default: 'No message provided'
jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        name: ["ubi8", "ubi10", "trixie"]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6
      - run: |
             if [[ "${{ matrix.name }}" == "trixie" ]]; then
             cat spideroak-deb-2016.asc | gpg --dearmor | tee spideroak.gpg > /dev/null
             fi
      - name: Build the Docker image
        run: docker build . --file Dockerfile.${{ matrix.name }} -t ${{ vars.DOCKERHUB_USERNAME }}/spideroak-${{ matrix.name }}:latest
      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker image
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/spideroak-${{ matrix.name }}:latest
      - name: Logout from Docker Hub
        run: docker logout
